import Head from 'next/head'
import Title from '../../modules/Title'
import Layout from '../../modules/layouts'
import Content from '../../modules/Content'

export default function SideProjects() {
	return (
		<Layout page="SideProjects">
			<Head>
				<title>Ben Cohen | Conversion Optimsation Specialist</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="stylesheet" href="https://use.typekit.net/puh4jzz.css" />
			</Head>
			<Title
				text="SideProjects"
			/>
			<div className="sideProjects page d-span-11 m-span-3">
				<Content
					key="project-6"
					title="loCRO"
					content={[
						<p key="loCro-p"> A tool to allow A/B tests to be developed on a local version of a clients website. Built with python, the tool will scrape the desired webpage, store all assets locally and integrate your development environment with it. In my case, it allowed me to make use of node modules such as browser-sync, sass and babel. </p>,
						<p key="loCro-p"> This tool not only speeds up development time by reducing time wasted on reloading the web page (which adds up to a surprising amount depending on the website) and also allows you to work offline, perfect for when travelling to meetings. </p>,
						<strong key="loCro-toolkit">Toolkit:</strong>,
						<p key="loCro-p">HTML / CSS / JavaScript / Python</p>
					]}
				/>
				<Content
					key="project-5"
					title="Classy Royale"
					content={[
						<p key="classy-royale-p">Clash Royale Ladder Game Tracker </p>,
						<p key="classy-royale-p">Using Python to handle the APIs and my knowledge of web development, I created a tool while on furlough to enable users to monitor and analyse their game performance. While the project was hindered by an understandably limited access to player data, this was a good side project as it allowed me to further develop my understanding of UI/UX design. Most of my work is focused on e-commerce and this project was the first opportunity I had to work on an analytical tool. </p>,
						<strong key="classy-royale-toolkit">Toolkit:</strong>,
						<p key="classy-royale-p">HTML / CSS / JavaScript / Python / Google Analytics / Hotjar</p>
					]}
				/>
				<Content
					key="project-4"
					title="Social Proof Messaging"
					content={[
						<p key="social-proof-messaging-p">Project used in A/B tests whilst working for iProspect</p>,
						<p key="social-proof-messaging-p">Built in PHP and JavaScript, this tool logs custom events to a database using a purpose built API and returns relevant information to be displayed back to the user.</p>,
						<p key="social-proof-messaging-p">The tool was used to display messaging such as "X people have bought this in the last Y hours"</p>,
						<strong key="social-proof-messaging-toolkit">Toolkit:</strong>,
						<p key="social-proof-messaging-p">HTML / CSS / JavaScript / Python / SQL</p>
					]}
				/>
				<Content
					key="project-3"
					title="enCapture"
					content={[
						<p key="enCapture-p">Exit intent behaviour targeted messaging.</p>,
						<p key="enCapture-p">Whilst at iProspect I aided in the development of a JavaScript function that detects exit intent behaviour and displays a popup modal to user, highlighting an offering or the website KSP's to retain the user's interest and aid them in progressing further down the funnel.</p>,
						<strong key="enCapture-toolkit">Toolkit:</strong>,
						<p key="enCapture-p">HTML / CSS / JavaScript</p>
					]}
				/>
				<Content
					key="project-2"
					title="This Site"
					content={[
						<p key="this-site-p">This site is always evolving, this design is actually the 9th since I started in 2016! I recently refactored and expanded the current design using NextJS</p>,
						<p key="this-site-p">The current version is served through Netlify and linked to the repo at <a rel="noopener noreferrer" href="https://github.com/BenC0/BenCoh-Miami" target="_blank">https://github.com/BenC0/BenCoh-Miami</a> </p>,
						<strong key="this-site-toolkit">Toolkit:</strong>,
						<p key="this-site-p">HTML / CSS / JavaScript / React / NextJS</p>
					]}
				/>
				<Content
					key="project-1"
					title="Misc."
					content={[
						<p key="misc-p">There are loads of small examples and projects done for the purpose of curiosity and learning on my <a rel="noopener noreferrer" href="https://codepen.io/Benco/" target="_blank">Codepen</a></p>,
					]}
				/>
			</div>
		</Layout>
	)
}
