import Head from 'next/head'
import Title from '../modules/Title'
import Layout from '../modules/layouts'
import Content from '../modules/Content'
import CallToAction from '../modules/CallToAction'

export default function Contact() {
	return (
		<Layout page="Contact">
			<Head>
				<title>Ben Cohen | Conversion Optimsation Specialist</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="stylesheet" href="https://use.typekit.net/puh4jzz.css" />
			</Head>
			<Title
				text="Contact"
			/>
			<div className="contact page d-span-11 m-span-3">
				<Content
					title="Get in touch"
					content={[
						<p key="tagline">If you'd like to get in touch, please do so via LinkedIn.</p>,
						<CallToAction
							key="linkedin-cta"
							link= "https://www.linkedin.com/in/bencro/"
							target= "_blank"
							text= "Ben Co"
							icon={<svg xmlns="http://www.w3.org/2000/svg" width="19.999" height="20" viewBox="0 0 19.999 20"><path d="M4.477,20H.33V6.648H4.477ZM2.4,4.827A2.413,2.413,0,1,1,4.8,2.4,2.422,2.422,0,0,1,2.4,4.827ZM20,20H15.858V13.5c0-1.549-.031-3.536-2.156-3.536-2.156,0-2.486,1.683-2.486,3.424V20H7.074V6.648h3.977V8.47h.058a4.358,4.358,0,0,1,3.923-2.156c4.2,0,4.968,2.763,4.968,6.353V20Z" transform="translate(0 -0.001)" fill="#fff"/></svg> }
						/>
					]}
				/>
			</div>
		</Layout>
	)
}
