import Head from 'next/head'
import Title from '../modules/Title'
import Layout from '../modules/layouts'
import Content from '../modules/Content'

export default function Home() {
	return (
		<Layout page="Home">
			<Head>
				<title>Ben Cohen | Conversion Optimsation Specialist</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="stylesheet" href="https://use.typekit.net/puh4jzz.css" />
			</Head>
			<Title
				text="Benji Cohen"
			/>
			<div className="home page d-span-11 m-span-3">
				<Content
					key="home-content"
					title="Conversion Optimisation Specialist"
					content={[
						<p key="home-content-p">I utilise my expertise in web development, UI/UX design and behavioural psychology to optimise websites from a wide variety of sectors to improve their performance.</p>
					]}
				/>
			</div>
		</Layout>
	)
}
